[tool.poetry]
name = "aiy-voice-assistant"
version = "0.1.0"
description = ""
authors = ["Ansar Nurzhanov <nansarik@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "2.7.16"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
